pipeline {
  agent any
  environment{
    IMAGE_NAME="kaswaladocker/static-site"
    IMAGE_TAG="${BUILD_NUMBER}"
  stages {
    stage('Build Image') {
      steps {
        sh 'docker build -t IMAGE_NAME:IMAGE_TAG .'
      }
    }
    stage('Push Image') {
      steps {
        sh 'docker push IMAGE_NAME:IMAGE_TAG'
      }
    }
     stage('Deploy to Kubernetes') {
      steps {
        sh '''
          kubectl set image deployment/static-site=$IMAGE_NAME:$IMAGE_TAG
        '''
      }
    }
  }
}
}
