pipeline {
  agent any
  stages {
    stage('Build Image') {
      steps {
        sh 'docker build -t kaswaladocker/static-site:1.0 .'
      }
    }
    stage('Push Image') {
      steps {
        sh 'docker push kaswaladocker/static-site:1.0'
      }
    }
  }
}
